; [bastion]
; 13.217.92.68 ansible_user=ubuntu ansible_ssh_private_key_file=C:\Users\TK-LPT-680\Downloads\Imb7-key.pem

; ; [app]
; ; 10.0.2.111 ansible_user=ubuntu ansible_ssh_private_key_file=C:\Users\TK-LPT-680\Downloads\Imb7-key.pem
; [app]
; 10.0.2.111 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/TK-LPT-680/.ssh/Imb7-key.pem ansible_ssh_common_args='-o ProxyCommand="ssh -i /mnt/c/Users/TK-LPT-680/.ssh/Imb7-key.pem -W %h:%p ubuntu@13.217.92.68"'


; [all:vars]
; ansible_user=ubuntu
; ansible_python_interpreter=/usr/bin/python3

[bastion]
52.205.1.221 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Imb7-key.pem

[app]
10.0.2.111 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Imb7-key.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/Imb7-key.pem ubuntu@52.205.1.221"'
; [app]
; 10.0.2.111 ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/TK-LPT-680/Downloads/Imb7-key.pem ansible_ssh_common_args='-o ProxyJump=ubuntu@52.205.1.221 -i /mnt/c/Users/TK-LPT-680/Downloads/Imb7-key.pem'


[jenkins]
52.205.1.221 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Imb7-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3

